talkgo/night

discuss/2018-05-09-wechat-discuss.md
=> init func not has ret value

discuss/2018-05-21-using-goroutines-on-loop-iterator-variables.md
add an answer to 1st question.
=> Create new pr to discuss

discuss/2018-06-07-dial-timeout-in-go.md, discuss/README.md
=> 增加tcp连接设置timeout讨论

articles/README.md, articles/sync/sync_rwmutex_source_code_analysis.md, articles/sync/sync_waitgroup_source_code_analysis.md
1. add article readme
2. add article title
=> change article readme

discuss/2018-07-02-c500k-on-linux.md
关于C100k的问题，都是今天下午讨论的内容，我做了资料收集，并提供了一些参考。
=> 关于C1000k问题的讨论

articles/sonarqube-for-golang/2018-07-22-sonarqube-for-golang.md
1. Fix Repository URL
2. Fix Image Path
3. Remove PDF
=> Update Sonarqube For Golang

discuss/2018-07-31-println-Println-and context.md
println函数与fmt.Println函数同时使用的区别，context如何使用
=> Create 2018-07-31-println-Println-and context.md

discuss/README.md
fix link error about 2018-08-24 数据库管理工具 GUI&CLI
=> fix link error

discuss/2018-09-05-git-system.md
=> add mutil param

README.md, articles/sync/sync_mutex_source_code_analysis.md
add sync.Mutex source analysis
=> feat(sync): add sync.Mutex

README.md, reading/20180906/2018-09-06-openfaas-guide.md
Signed-off-by: qinpengfei <qinpengfei@jd.com>
=> fix: typo error about OpenFaas

articles/sync/sync_rwmutex_source_code_analysis.md
=> feat(sync.RWMutex): update sync.RWMutex

articles/sync/sync_waitgroup_source_code_analysis.md
添加sync.WaitGroup中对State()的解析。
修改文件：articles/sync/sync_waitgroup_source_code_analysis.md
=> 添加sync.WaitGroup对State()中判断的解析

README.md, content/index.md
=> 修复点击贡献链接错误

content/discuss/2018-12-25-macOS-time-synchronization.md
=> fix date format.

content/reading/2018-12-23T210500.md
在尽量贴合 《第 24 期 go mod 源码阅读》视频内容的同时，增加/完善了文字版本的描述和介绍。
=> Add go mod reading article.

content/discuss/2019-01-10-anlayze-range.md
=> 关于range的一些不易察觉的"坑"

content/reading/2018-11-08-http-router-in-go.md
=> Update 2018-11-08-http-router-in-go.md 

content/daily-reading/1-2019-03-14.md
https://reading.developerlearning.cn/daily-reading/1-2019-03-14/
- 表格渲染错误，好像是因为行尾多了空格
- 中文排版优化，参考 https://github.com/jxlwqq/chinese-typesetting
=> fix(daily_reading): fix table render and chinese typesetting

config.toml, themes/hugo-material-docs/layouts/_default/single.html, themes/hugo-material-docs/layouts/partials/comment.html
#172 
添加 gitalk 评论组件，需要到 https://github.com/settings/applications/new 注册一个 Github OAuth application。
参见 https://github.com/gitalk/gitalk#usage
=> add gitalk comment

content/discuss/2019-03-08-wechat-discuss.md
=> RWMutex 增加源码分析

content/discuss/2019-03-26-gopsutil.md
=> 新增《系统指标采集》微信讨论

README.md, content/index.md
=> docs(reading): preview golang/sync

README_EN.md
=> docs(README): add readme english version

README.md, README_DE.md
=> Deutsche Version von README

content/reading/40-2019-04-27-atomic-value-in-go.md
=> docs(reading): atomic.Value usage and reading source

content/discuss/2019-06-19-gorm-mysql-timestamp.md, content/discuss/2019-06-19-gorm-timestamp.md
整理Go、Gorm与MySQL中timestamp交互时遇到的问题
=> Go、Gorm与MySQL中timestamp交互时遇到的问题

content/reading/58-2019-09-05-whats-new-in-go1.13.md
=> docs(reading): go1.13 reading

HISTORY.md
添加 Go 夜读 HISTORY 第十阶段
>Go 夜读 SIG 核心小组的组建。
=> docs(HISTORY): update reading-go history

content/reading/60-2019-09-19-ipfs-guide.md
=> docs(README): reading 60 ipfs

README.md
1. 更新项目名称为：`night-reading-go`
2. 更新 Slack Invite Link
=> docs(README): update name to night-reading-go

content/reading/62-2019-10-10-go-micro-part1.md
=> reading #62

content/discuss/2018-12-11-wechat-discuss.md, content/discuss/2019-10-13-go-module-looping-package.md
go mod下出现looping trying to add package
=> go mod下出现looping trying to add package

content/interview/articles/interview_analysis_4.md
https://github.com/developer-learning/night-reading-go/pull/539
=> fix: interview_analysis_4.md [35]

content/articles/goroutine_and_channel/README.md
=> 增加goroutine和通道内容

content/index.md
1. fix slack invite url
2. replace readme content to reading index.
=> chore(content/index): fix slack invite url

content/reading/81-2020-03-19-gorm-guide.md
=> docs(reading): add 81 reading gorm

themes/hugo-material-docs/layouts/partials/footer_js.html
=> chore: handle links for side menus

content/home.md
talkgo.org 主页没有更新，他们存在于 content/home.md
=> fix: png link

.github/ISSUE_TEMPLATE/share_request.md, .github/ISSUE_TEMPLATE/share_template.md
fix can't choose a issue template.
- https://help.github.com/en/github/building-a-strong-community/configuring-issue-templates-for-your-repository
=> fix(issue_template): add name to choose issue template

README.md, content/home.md, content/night/87-2020-04-29-goland-tips.md
##Background
JetBrains GoLand 2020.1 新特性介绍
Florin Pățan & 范圣佑
fix: #617
=> chore(reading): update 87

content/night/104-2020-09-13-hashicorp-raft.md
=> docs: 104 hashicorp/raft 文字版

content/articles/sync/sync_Map_source_code_analysis.md
=> Fix typo in sync_Map_source_code_analysis.md
